#
#
#

PWD = $(shell pwd)
ROOT = $(PWD)/../..

CC = gcc
CXX = g++
ISL_INCLUDE = $(ISL_HOME)/include
CFLAGS += -I$(ISL_INCLUDE)
CXXFLAGS += $(CFLAGS)
LDFLAGS += -L$(HOME)/lib -lisl

target: test_driver

